services:
  dynamic-deno-server:
    build: .
    ports:
      - "9999:9999"
    volumes:
      - /opt/functions:/opt/functions
      - /opt/logs:/opt/logs
    environment:
      - ENABLE_LOGS=true
    privileged: true
    restart: unless-stopped
