services:
  dynamic_deno_server:
    privileged: true
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - ENABLE_LOGS=true
    volumes:
      - /opt/functions:/opt/functions
      - /Users/pierrecabriere/Desktop/logs:/opt/logs
    ports:
      - "9999:9999"
