services:
  dynamic-deno-server:
    build: .
    ports:
      - "9999:9999"
    volumes:
      - ./.tmp/functions:/opt/functions
      - ./.tmp/logs:/opt/logs
    environment:
      - SAVE_LOGS=true
      - HEALTH_CHECK_ATTEMPTS=5
      - PORT=9999
      - ENV_JSON={"KEY1":"value1","KEY2":"value2"}
      - ENV_FILE=./.env
      - LOG_FORMAT=cri
      - WATCH_FILES=true
      - DEBUG=*
      - PUBLIC_DENO_FOO=baz
      - PUBLIC_DENO_BAR=qux
    restart: unless-stopped
