services:
  dynamic-deno-server:
    build: .
    ports:
      - "9999:9999"
    volumes:
      - ./.tmp/functions:/opt/functions
      - ./.tmp/logs:/opt/logs
    environment:
      - ENABLE_LOGS=true
      - HEALTH_CHECK_ATTEMPTS=3
      - SERVICE_PORT=9999
      - SERVER_ENVIRONMENT={"KEY1":"value1","KEY2":"value2"}
    privileged: true
    restart: unless-stopped
